bettersg/tobeyou_facilitator

.firebaserc, .github/workflows/firebase-hosting-merge-release.yml, firebase.json
This adds the github action to deploy the `tobeyou-facilitator` app to firebase (facilitator.tobeyou.sg) on merge to `release`.
=> Add github actions

src/components/dashboard/NewRoomModal.jsx
This adds an organisation field to the new room modal. Its default value is set to the user's organisation, but it can be changed if the user wants it to be different.
=> Add organisation field when creating a new room

src/components/dashboard/NewRoomModal.jsx
Remove adding of co-facilitators when adding a new room
=> Remove co-facilitator emails

src/App.js, src/components/dashboard/CompletionRate.jsx, src/components/dashboard/Home.jsx, src/components/dashboard/NewRoomModal.jsx, src/components/dashboard/Quizzes.jsx, src/components/dashboard/Reflections.jsx, src/components/dashboard/Room.jsx, src/components/dashboard/RoomCard.jsx, src/models/quizAnswerModel.js, src/models/reflectionResponseModel.js
Each chapter in each room gets a separate room card:
Within a room, we can navigate to look at its completion rate, its reflections, and its quiz answers:
=> Add room page skeleton

src/components/dashboard/Quizzes.jsx, src/components/topbar/Topbar.jsx, src/models/miniGameMap.js
This adds a basic view for minigame results, with all the questions and a response count for each of its answers
Here the `miniGameMap` is directly copied from the other repo
=> Add minigame results

src/components/dashboard/NewRoomModal.jsx, src/components/dashboard/RoomCard.jsx
This adds basic character/chapter selection in the new room modal. There still needs to be validation, e.g. at least 1 chapter should be selected
=> Add chapter selection

src/components/dashboard/Home.jsx, src/components/dashboard/RoomCard.jsx, src/models/roomModel.js
Adds the display of dates and characters and chapters, the background color corresponds to active/archived, styling is still minimal
=> Improve room card layout

src/components/dashboard/Home.jsx, src/components/dashboard/NewRoomModal.jsx, src/components/dashboard/Room.jsx, src/components/dashboard/RoomCard.jsx, src/models/storyMap.js
=> Add room chapter selection and upcoming filter

src/components/dashboard/Reflections.jsx
This adds an updated reflection page, along with a reflection modal popup when a particular reflection is clicked. Left/right arrows can be used for navigation
=> Add reflection modal

package-lock.json, src/components/dashboard/Reflections.jsx, src/components/styled/Dashboard/reflections.jsx
This adds functionality to navigate with left/right keys, and some base styling for the reflections
=> And reflection modal and card styling

src/App.js, src/components/auth/AuthLayout.jsx, src/components/auth/ProfileBuilder.jsx, src/components/auth/SignUp.jsx, src/components/topbar/Sidebar.jsx, src/models/userModel.js
Fixes #15 
This adds a basic profile builder page. The UI is not ideal (there is no styling done), but the functionality to save a user's profile details is there.
We still need to allow custom text inputs for 'Other' values, though we'll need a design for how that's going to look like
=> Add profile builder

.eslintignore
Part of #19, it removes any build files from eslint checks
=> Change .eslintignore

src/components/dashboard/NewRoomModal.jsx, src/models/roomModel.js
This PR adds a `createdAt` field to a room. This field can be later used for tracking whether a participant has completed a chapter (if it's completed after the room was created)
=> Add `createdAt` field to room

src/App.js, src/components/RoomCard/RoomCard.jsx, src/page/CompletionRate.jsx, src/page/GameChoices.jsx, src/page/Quizzes.jsx, src/page/Reflections.jsx, src/page/Room.jsx
Part of #26 
This PR updates the room page to roughly follow the new format, no styling has been done yet. Room page now displays all chapters at one go.
=> Change room page

src/components/RoomCard/RoomCard.jsx, src/components/dashboard/NewRoomModal.jsx, src/models/roomModel.js, src/page/Home.jsx
This PR adds the soft delete functionality. When users delete rooms, they'll only be hidden from view.
The field `isDeleted` is added to all rooms: it is `false` by default, and when the user deletes the room it's set to `true`.
=> Add soft deletes

src/page/Reflections.jsx
=> Show only non-empty reflections

src/components/GeneralRoomModal/NewRoomModal.jsx
Fixes #43
Uses both lowercase and uppercase characters for the room code
=> Use lowercase characters for room code generation

src/models/globalVarMap.js, src/models/savedStateModel.js, src/page/GameChoices.jsx, src/utils.js
Part of #51 
This PR adds game choices - no styling yet, but the all functionality for pulling information is added
=> Add game choices

src/App.js, src/components/RoomCard/RoomCard.jsx, src/models/roomModel.js, src/page/EngagementLevels.jsx, src/page/GameChoices.jsx, src/page/Quizzes.jsx, src/page/Reflections.jsx, src/page/Room.jsx
=> Change URLs to use room code instead of room id

src/page/Home.jsx
Not important and might want some designer input for this - adds a confirmation for some actions. just a quick solution to prevent accidentally deleting rooms!
=> Add confirmations for deleting and archiving rooms

src/models/reflectionIdMap.js, src/models/storyMap.js
This PR adds the chapters for Ravi, allowing the user to create/edit rooms and see data (reflections, quizzes, game choices etc.) related to Ravi's chapters
Pending: still need chapter timings (X min) + an avatar image for Ravi
=> Add Ravi chapters

src/App.js, src/page/ForgetPassword.jsx
Fixes #60
This PR adds a page to reset the user's password on clicking the "Forgot your password?" option on the login page. Works similarly to the one on https://game.tobeyou.sg/forget-password.
There's some duplication across the login, sign-up, and forget password pages - might want to refactor these pages
=> Add forget password page

src/components/Topbar/Topbar.jsx
=> Add play game link

src/components/GeneralRoomModal/GeneralRoomModal.jsx, src/models/storyMap.js
Fixes #53. This PR removes the estimated assigned time
=> Remove estimated assigned time

src/App.js, src/components/GeneralRoomModal/GeneralRoomModal.jsx, src/contexts/SnackbarContext.jsx, src/page/ForgetPassword.jsx, src/page/Login.jsx, src/page/SignUp.jsx
Part of #27
This PR adds the snackbar. The current ad-hoc solution (browser alerts) is replaced with the snackbar, just like in the main game
=> Add snackbar

src/components/ChoicesScreen/ChoicesScreen.jsx, src/components/GeneralBreadcrumbs/GeneralBreadcrumbs.jsx, src/components/GeneralBreadcrumbs/StyledBreadcrumbs.jsx
Addresses https://github.com/bettersg/tobeyou_facilitator/pull/76#discussion_r867298570 and https://github.com/bettersg/tobeyou_facilitator/pull/76#discussion_r867300344
Switched out links to react-router links, which improves page loading times. there's a little duplication in `GeneralBreadcrumbs.jsx` unfortunately :(
=> Change hrefs to react router links

src/page/Room.jsx
Fixes #81
Removes edit icon and download report button
=> Remove unused buttons from room page

src/contexts/AuthContext.jsx, src/models/userModel.js, src/page/ForgetPassword.jsx, src/page/Login.jsx, src/page/ProfileBuilder.jsx, src/page/SignUp.jsx
Fixes #88 
- User input for the `organisation` field is shifted from creating an account -> profile builder (see screenshot below)
- Signing in/creating an account is now the same as the main game - all users with a main game account can sign in, without needing to create a separate facilitator dashboard account
- Setting of `isFacilitator = true` now happens after completing the profile builder
The organisation text field above is uncustomized, will still need to tweak its appearance: spacing, height, background color, corners, height etc.
=> Update flow for signing in and creating an account

package-lock.json, package.json, src/firebase.js, src/page/Login.jsx
Fixes #86
Still needs to be tested (esp FB logins, which I don't have): may only work in production
Like the main game, these social logins don't work on localhost/staging
=> Add social logins

src/components/GeneralRoomModal/QrModal.jsx, src/page/Home.jsx, src/page/Room.jsx
Part of #93 
This PR adds the QR modal to the room page. Also done some refactoring of the room page + shifted the class code to the bar on top, while removing the people icon (leaving only the QR icon).
=> Add QR modal to room page

public/index.html
=> Update website meta tag description

src/page/Room.jsx
Resolves #94
This PR adds the completion rate modal, which shows a list of participant emails and whether they've completed the given chapter.
The emails have to be fetched one user at a time from the database, which could be expensive if there are many students in the room
=> Add completion rate modal

src/components/ChartScreen/ChartScreen.jsx
=> Remove chart arrows for left/rightmost options

src/models/globalVarMap.js, src/page/GameChoices.jsx, src/page/Room.jsx
=> Add chapter endings to game choices

.eslintrc.json, .github/workflows/lint-pull-request.yml, package.json, src/components/GeneralButton/GeneralButton.jsx, src/components/GeneralButton/GeneralButton.mdx, src/components/GeneralButton/StyledButton.jsx, src/components/GeneralSelect/GeneralSelect.jsx, src/components/GeneralSelect/GeneralSelect.mdx, src/components/GeneralSelect/StyledSelect.jsx, src/components/GeneralTextField/GeneralTextField.mdx, src/components/GeneralTextField/StyledTextField.jsx, src/components/HomeToggleButtonGroup/HomeToggleButtonGroup.jsx, src/components/Modals/GeneralRoomModal.jsx, src/components/RoomCardTag/RoomCardTag.jsx, src/components/RoomCardTag/StyledRoomCardTag.jsx, src/components/Topbar/StyledTopbar.jsx, src/components/Topbar/Topbar.jsx, src/components/styled/auth.jsx, src/contexts/AuthContext.jsx, src/index.css, src/index.js, src/page/DashboardLayout.jsx, src/page/Reflections.jsx, src/page/RequireAuth.jsx
Resolves #19 
- Fixes remaining lint issues in the codebase
- Fixes remaining style issues (ran prettier on all files)
- Sets up the script `npm run lint` to run eslint checks
- Adds automated lint checks via github actions
=> Add lint checks and fix remaining lint and style issues

src/components/GeneralTextField/GeneralTextField.jsx, src/components/GeneralTextField/StyledTextField.jsx, src/components/Modals/GeneralRoomModal.jsx, src/page/ForgetPassword.jsx, src/page/Login.jsx, src/page/ProfileBuilder.jsx
Fixed styling and spacebar input issue
=> Fix textfield input

src/components/Modals/GeneralRoomModal.jsx
Resolves #114 
Adds whatsapp sharing, email sharing, and copying to clipboard
=> Add options to share room with class

src/page/Login.jsx
Fixes #113 
This PR adds a notice on the login page to tell users that the site is not mobile-friendly. Does this message work?
=> Add non-mobile friendly warning to main page

package-lock.json, package.json, src/models/quizAnswerModel.js, src/models/savedStateModel.js, src/page/GameChoices.jsx, src/page/Quizzes.jsx, src/page/Room.jsx
Closes #126
This PR adds a download button for rooms on the top right-hand corner of the rooms page. It will fetch all relevant data for the room (reflections, game choices, quiz answers) and display them in 3 spreadsheets in a .xlsx file.
Some refactoring was also done for the chart datas, so that the data for game choices and quiz answers can be used both for the charts and downloads
=> Add download feature for rooms

src/models/globalVarMap.js, src/models/storyMap.js
Added all the endings for Chapters 1 - 3
Added all the key variables for all chapters. Chapter 3 is tricky because of the forked storyline (not all players will experience the same variables).
=> Updated the StoryMap for Unaisah
